### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by daichi-code** [daichi-code/furima-30534#11]
フリマアプリのURL
https://furima-30534.herokuapp.com/

Basic認証
daichi / 1102

出品者用のメールアドレスとパスワード 
mail : aaa@aaaa
password : aaa111

購入者用のメールアドレスとパスワード 
mail : sss@sss
password : sss111

購入用カードの番号・期限・セキュリティコード
4242424242424242
3/33
123

**Comment by mutorisa** [comment]
小山さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by daichi-code** [comment]
ありがとうございます！
間違って追加機能を行ってしまいましたが問題なく動作していますのでこのままにしたいと思います！
